language: go
env:
- GO111MODULE=on
# - GO111MODULE=off
go:
- "1.11.x"
- "1.12.x"
- tip
matrix:
  allow_failures:
  - go: tip
install:
- go get github.com/fortytw2/leaktest
- go get ./...
script:
- go test -race -v ./...
