version: '3.3'

services:
  elasticsearch5:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.14
    hostname: elasticsearch5
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=mia5
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch5:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
  kibana5:
    image: docker.elastic.co/kibana/kibana:5.6.14
    hostname: kibana5
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=mia5
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./etc/kibana5/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 29210:5601
  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    hostname: elasticsearch6
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=mia6
      # Disable to run on Docker for Mac for Kubernetes
      - bootstrap.memory_lock=true
      #- xpack.security.enabled=false
      #- xpack.monitoring.enabled=false
      #- xpack.ml.enabled=false
      #- xpack.graph.enabled=false
      #- xpack.watcher.enabled=false
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch6:/usr/share/elasticsearch/data
    ports:
      - 19201:9200
  kibana6:
    image: docker.elastic.co/kibana/kibana-oss:6.5.4
    hostname: kibana6
    volumes:
      - ./etc/kibana6/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 19211:5601
